SELECT
    TRADE_DT AS 交易日期,
    B_ANAL_CURVENAME AS 曲线名称,
    B_ANAL_CURVETERM AS 交易期限,
    B_ANAL_YIELD AS 到期收益率
FROM
    wind.CBondCurveCNBD
WHERE
    B_ANAL_CURVENAME IN ({})
    AND B_ANAL_CURVETYPE = 2
    AND B_ANAL_CURVETERM IN ({})
    AND TRADE_DT BETWEEN :start_date AND :end_date
ORDER BY
    TRADE_DT DESC,
    B_ANAL_CURVENAME,
    B_ANAL_CURVETERM